### ISSUE TITLE
Evaluation Checklist

### ISSUE THREAD

**Issue by LouisJenkinsCS** [LouisJenkinsCS/Distributed_Queue#10]
@e-kayrakli 

The other threads got kind of cluttered, so I wanted to make a new one with, in particular, a checklist. I'm also getting side-tracked a lot so this is to refocus myself. It actually isn't that much! Data Structures can be easily made in about 30 min, Micro Benchmark is pretty easy (although NQueens I'll need to ensure its correct and properly demonstrates performance, etc), and Work Depletion is easy as testing during the micro benchmark for dequeue. Boom! Its smooth sailing... so long as more compiler issues don't arise (which seem to crop up about 4 - 5 times a week now)

## Proof-Of-Concept(s)

Currently, I have two of them, the original (strictly FIFO) and new work stealing one (MPMC). The strictly FIFO one I know already works just fine although it doesn't scale due to communications, but may as well be included. The MPMC one is lacking work stealing currently (and I know you said not to worry about it, but I *definitely* need to do it before I can call it a proper Proof-Of-Concept. While FIFO doesn't have to scale, MPMC *does*.

- [ ] Satisfactory

## Data Structures

I'm wondering if the 'distributed vs non-distributed' versions can just compare to baseline at 1 locale, since no communication is performed then.

- [x] Distributed Data Structures
   - [x] FIFO
      * Potential race condition
      * Enqueue scales, but Dequeue does not
         * Planned revision to allow both to scale under all conditions (including contention)
   - [x] MPMC
      * Work stealing is in a workable Proof-Of-Concept state but not viable for usage
         * Requires some low-level C logic for manageable performance and semantics
      * The local queue logic is embedded into the data structure, and uses a sync two-locked queue
         * Need to create separate paths: One for Sync, One for CC-Synch

- [x] Local Data Structures
   - [x] Sync Two-Locked Queue
   - [x] CCQueue
   - [x] Sync List (Non-Distributed)

## Benchmarks

This has been discussed in issues #1 and #2 but in general I want to create the actual checklist here so I can keep everything in one place.

- [x] Micro benchmark (Raw Enqueue + Dequeue)
   - [x] Enqueue 
   - [x] Dequeue
   - [x] Computational Intensity
      * Needs to be checked/confirmed
   - [x] Artificial Irregularities
      * Needs to be checked/confirmed
- [ ] NQueens

## Proof-Of-Correctness

- [x] Work Depletion
   * Implemented in the main method of `DistributedQueue.chpl`
- [x] FIFO Test
   * Since the original `DistributedFIFOQueue` scales, I need to ensure it is actually FIFO!

## Repository State

Stated in issue: #6 I need to organize it more. 

## Script

Besides a basic makefile, it was mentioend here: #2 

- [ ] Run All or Subset of Micro-Benchmarks
   * Differs from a simple makefile that builds all `chpl` files together and specifies `--main-module`
- [x] Properly sets up environment variables
- [ ] Logs SHA hash and Chapel version
   * Likely just `chpl --version` concatenated with `git rev-parse HEAD`
- [x] Log Performance Metrics
   * How do I do this? What am I logging that the benchmark isn't? I think I already am
- [x] Plotting
   * Currently I'm doing this.
- [ ] Versatility
   - [ ] Adding new benchmarks
      * Planned to just change `--main-module` to run the benchmark and compile everything together. This may not be possible though.

**Comment by e-kayrakli** [comment]
What is "Work Depletion"?

**Comment by LouisJenkinsCS** [comment]
Work Depletion would ensure that all work has been consumed from the work queue.  Its specific to MPMC which doesn't need a test to ensure it is FIFO. This would ensure that, from a combination of work stealing and normal local dequeues, *all* work from the queue is consumed. More of a test for undefined behavior and the like in implementation.

**Comment by e-kayrakli** [comment]
Oh yeah, at the end you should definitely have queue.size == 0

This is about correctness and much more important than performance.

**Comment by LouisJenkinsCS** [comment]
Its not just `queue.size == 0` though, or that all `localQueue.size == 0` (or in this case, `localQueue.head == localQueue.tail`), but that the elements themselves are removed. I was thinking defining a range of elements, say `1 .. nElements`, distributed across each. That way if any of them are missing, then I know it doesn't work. In fact, it could be added to the computation being done between each operation, too! The next issue though would be communication because elements can be stolen across locales, so it would need to be global. I suppose a simple global distribution could do, but I worry it will inject some non-determinism (I.E: in one benchmark, most communications were local or closer in proximity, in another it was further and mainly remote, etc.)

Hm... I guess I can collect locally, then compare *after* it finishes!

**Comment by e-kayrakli** [comment]
Especially for synthetic benchmarks where you'd have dual coforalls you can store task local checksums and then sum reduce them after the timed region.

```chapel
coforall l in Locales do on l do
  coforall tid in 0..#here.maxTaskPar do
    var taskLocalChecksum = 0;
    // do your timed benchmark loop here
    globalCSum.fetchAdd(taskLocalChecksum)
```

Your checkusm must be the same for any number of locales and threads per locales.

**Comment by LouisJenkinsCS** [comment]
Interesting approach. I can then chunk it manually per task per locale. Interesting. Perhaps (outside of NQueens), I can intermingle enqueue and dequeue into a single benchmark by assigning half to enqueue and other half to dequeue for a raw 'combined' performance.

**Comment by LouisJenkinsCS** [comment]
I just realized... work stealing will be harder than I originally thought! I keep forgetting the limitations of Chapel. For work stealing to work, I'd need custom operations, which needs a custom queue inline and specifically for the distribution. I see why you had yours like that in your `DistributedUList`, you kind of *need* that freedom. I need the ability to steal from other locales, and that isn't possible without some major modifications that would be ugly (I.E: Access to fields required to do the stealing), and we can't just use a more *functional* approach as first class functions aren't stable... and due to the type system and algorithm for `CC-Synch`... definitely need to inline *all* of the logic. I suppose since I'm strapped for time, normal `sync` variables can work for replacement until appropriate. 

You *did* say it was optional and more of a 'plus' and could wait until after. Hm... I don't like just leaving things like this unfinished.

**Comment by e-kayrakli** [comment]
I do not know any other distributed programming paradigm where work stealing could be done easier!

Not to say that it is easy, but I am surprised you find Chapel limiting you for work stealing.

P.S I have to say that I don't understand what you mean by "inline"..

**Comment by LouisJenkinsCS** [comment]
Well I didn't mean in terms of distributed programming, I meant in general programming. I've never used the others though, but I'm sure that Chapel is *much* higher in terms of abstraction.

By inline, I meant the fact that logic needs to be performed then and there. Like my example for work stealing, a normal synchronized queue needs to hold the lock while attempting to steal work, but unless you either expose the lock (which now that I think about it, definitely seems like the actual solution here for a normal `sync` variable...) or make modifications so work stealing can be done inside of the queue (I.E: Knowing what other queues to steal from), its not possible to do so (efficiently).

**Comment by LouisJenkinsCS** [comment]
@e-kayrakli 

MPMC now seems to work and pass the "Work Depletion" test, although the algorithm for work stealing is horrible. I remember why I had so much trouble with 'Enqueue_Async', but looking at how you handle something similar in your code, can you explain [this](https://github.com/e-kayrakli/distributed_list/blob/master/DistributedUList.chpl#L357-L397) for me. 

I get the basics of it... you allocate enough space with `c_malloc`, and then use the primitive `chpl_comm_array_get` to read it in a single network communication. I'm wondering, is there a `c_realloc` as well, or should I know the exact amount to be transferred (meaning using a normal chapel array, then allocating a C array)? Currently, I have a work buffer declared as such...


```chpl
var work : [{0 .. numLocales-1}] (bool, eltType);
```
Where I had to allocate it statically (or else incur communication costs), and since it was static, if the other queues to be stolen from were empty I had no way of knowing if what was there was valid or not, so I coupled it with a `bool` in a tuple. As you can see its inefficient...

But, with that approach, perhaps I can couple the size with the pointer to the data itself! I'd need something like you have, [here](https://github.com/e-kayrakli/distributed_list/blob/master/DistributedUList.chpl#L36-L38). It'd be able to couple it to each locale-specific data! Am I on the right path here?

**Comment by LouisJenkinsCS** [comment]
Would like to report a roadblock where I am prevented from progressing towards providing a benchmark that allows us to run multiple types of queues due to it resulting in an internal segfault. The file is [here](https://github.com/LouisJenkinsCS/Distributed_Queue/blob/trunk/benchmark/benchmark.chpl), and can be reproduced in trunk by running `make Benchmark`. I honestly don't have *any* idea how to proceed right now, because I cannot compare more than one type of `Queue` anymore, and there is no way to determine *what* causes the error.

```
LouisJenkinsCS@MSI:/mnt/c/Github/Distributed_Queue$ make Benchmark
chpl --devel --fast queues/Queue.chpl queues/local/SyncQueue.chpl queues/local/CCQueue.chpl \
        benchmark/cclock.chpl queues/distributed/DistributedFIFOQueue.chpl queues/distributed/DistributedQueue.chpl \
        benchmark/benchmark.chpl misc/LocalAtomicObject.chpl \
        -o bin/main.exe --main-module benchmark
queues/distributed/DistributedFIFOQueue.chpl:106: warning: The `ReplicatedDist` domain map is deprecated.  Please switch over to using `Replicated` instead.
internal error: seg fault [misc.cpp:558]
make: *** [Benchmark] Error 1
```

Note that the warning does not cause it nor will it resolve the issue. I have have to use `ReplicatedDist` over `Replicated` to run on swan. **Also this bug is present in both release and in master.**

**Comment by e-kayrakli** [comment]
OK will take a look into this today.

Edit: Just by looking at your benchmark code, here is a shot in the dark that may help you get over the roadblock: Make your flags controlling the queue type `params` and the `getQueue` function a param function. Modify your makefile so that you generate multiple executables: one for each queue type. And modify your scripts to create PBS jobs for each executable you generate. This will remove all the dynamic dispatch logic. (I haven't dug deep, at all. So it is early for me to say that this will definitely solve the issue)

>  I have have to use ReplicatedDist over Replicated to run on swan

You don't have to stick with the module on swan, though right? In fact, I recommend against it and using master on swan, as well.

**Comment by LouisJenkinsCS** [comment]
Oh yeah Engin, [this](https://github.com/LouisJenkinsCS/Distributed_Queue/issues/10#issuecomment-310861968) comment I believe I need a reply for as well, its in regards for how to advance with work stealing.

**Comment by e-kayrakli** [comment]
>I get the basics of it... you allocate enough space with c_malloc, and then use the primitive chpl_comm_array_get to read it in a single network communication. I'm wondering, is there a c_realloc as well, or should I know the exact amount to be transferred (meaning using a normal chapel array, then allocating a C array)? Currently, I have a work buffer declared as such...

Even if there is a c_realloc, wouldn't you need to know the size of data you are bringing in? Storing/queueing the total size would probably need an additional communication. Which I believe I already have in my implementation (I don't remember exact details, haven't looked at it in a while)

Also, this implementation doesn't do work stealing strictly. What it does is more of a redistribution of data according to some user-specified rules. Which may or may not have ideas applicable to work stealing. (Work stealing was something crucial for this project, but I never got around implementing it, and am doubtful I will do that soon.)

> But, with that approach, perhaps I can couple the size with the pointer to the data itself! I'd need something like you have, here. It'd be able to couple it to each locale-specific data! Am I on the right path here?

I have done something like this for my research in a slightly irrelevant case: do one communication to PUT a heterogeneous tuple with (size, c_ptr), than do a GET from the other locale according to what you have received before. (Admittedly, not knowing the exact details what you meant) The idea seems reasonable.

**Comment by LouisJenkinsCS** [comment]
> Even if there is a c_realloc, wouldn't you need to know the size of data you are bringing in? 

I was a bit unclear with my need for `c_realloc`. I meant to dynamically resize buffer locally while stealing work, but then again I just remembered that I know precisely how many elements are present and just how many I should steal, so I already know how much space to allocate with `c_malloc`.

> I have done something like this for my research in a slightly irrelevant case: do one communication to PUT a heterogeneous tuple with (size, c_ptr), than do a GET from the other locale according to what you have received before.

That makes sense. Now I have one more question...

What are the exact arguments that `chpl_comm_array_get` accepts? It looks like in C equivalent, its `(void *srcBuffer, int srcLocId, void *destBuffer, size_t bufSize)`? However, looking at it, you have the following code

```chpl
__primitive("chpl_comm_array_get", dest.incomingBufs[srcId][0],
                                         srcId,
                                         src.outgoingBufs[here.id][0],
                                         bufSize);
```

However, the types of those `outgoingBufs` and `incomingBufs` is the following...

```chpl
var outgoingBufs: [Locales.domain] c_ptr(eltType);
var incomingBufs: [Locales.domain] c_ptr(eltType);
```

Is this implying that you can dereference a `c_ptr` by indexing into it? Does this also imply that I can assign elements by indexing into the pointers directly? If thats the case, then

`outgoingBufs[srcId][0]` would be a dereference... I'm assuming what it does is that the compiler transforms it into the equivalent: `incomingBufs[0] = outgoingBufs[0]`? Then does it offset into the buffer as well from `0 .. sizeof(eltType) * bufSize`? Sorry, a bit confused here, I'm assuming if I incorrectly use this it will crash, so I need to know the full semantics.

**Comment by e-kayrakli** [comment]
> Is this implying that you can dereference a c_ptr by indexing into it? Does this also imply that I can index into the pointers directly?

Definitely.

Since there are no pointers in Chapel, this primitive's arguments are by-value. Compiler adds the "address-of" in an ad-hoc manner. It may be a bit confusing if you are considering primitives as functions. (i.e. there are no argument passing etc. so your intuitions about pass-by-value, pass-by-reference can be misleading)

Does that answer your question?

**Comment by LouisJenkinsCS** [comment]
I'm still a bit confused. So if I had a variable declared like such...

```chpl
type eltType;
var ptr : c_ptr(eltType);
```

Then you're saying that, by default, to get the value of the pointer, I can do...

```chpl
var elt : eltType = ptr[0];
```

As well, if I wanted to, I can assign it as such...

```chpl
ptr[0] = _defaultOf(eltType);
```
That is correct, right?

> Compiler adds the "address-of" in an ad-hoc manner.

Hmm... so you mean that the compiler will do the following...

`&incomingBufs[0] = &outgoingBufs[0]` which is why the extra dereference is needed? Does this work for non `c_ptr` types? If we want to send a tuple over, say `(size, c_ptr(eltType))`, then how would this work? Or would we not need to use `chpl_comm_array_get` because we can just use Chapel communication (inter-locale assignment)? Then to cleanup the `c_ptr` I'd need to jump to the owning locale and do a `delete ptr`, or else it would attempt to free (and corrupt) memory locally.

I'm trying to gauge pros and cons here... Comparing this to, say, resizing the domain of the second dimension of the array with the correct size, and then transferring it in bulk...

```chpl
var workBuf : [Locales.domain] [/* Configurable domain??? */] eltType;
on Locale[idx] {
   // ...
   workBuf[here.id][/* Somehow resize domain so that it is the number of elements... */] = elt;
   // ...
}
```

Actually... on second thought, I think `c_malloc` is the way to go. This is the same issue I've run across before.

Edit:

Nevermind, I think I see how to do it with Chapel.

```chpl
coforall loc in Locales {
   var dom = { 0 .. 0 };
   var arr : [dom] eltType;
   on loc {
      // ...
      // Resize and bulk transfer
      dom = { 0 .. newSize };
      arr = localArr;
   }
   // Merge with other tasks
}
```

**Comment by e-kayrakli** [comment]
> That is correct, right?

Yes. All of the above is correct.

> so you mean that the compiler will do the following... &incomingBufs[0] = &outgoingBufs[0] which is why the extra dereference is needed?

Sort of.. to be sure, what it does is more of a `memcpy(&incomingBufs[0], &outgoingBufs[0], bufSize)`. Only replace memcpy with appropriate GET.

> If we want to send a tuple over, say (size, c_ptr(eltType)), then how would this work? Or would we not need to use chpl_comm_array_get because we can just use Chapel communication (inter-locale assignment)? Then to cleanup the c_ptr I'd need to jump to the owning locale and do a delete ptr, or else it would attempt to free (and corrupt) memory locally.

I am assuming you are going to need to do this in a scenario as follows (lmk if I misunderstood your use case)

Locale A needs to copy some stuff from locale B. Locale B creates a tuple of type `(int, c_ptr(eltType)` where A can read. Then, A can do a simple tuple assignment to get this tuple. Followed by a GET to get the actual data. A Chapel-y pseudocode:

```chapel
on A {
  const (size, remoteAddress) = someTuple; //someTuple is actually on B
  var myLocalBuffer = c_malloc(size, eltType);
  chpl_comm_array_get(myLocalBuffer[0], B, remoteAddress[0], size); //this should be a primitive in practice
}
```

On array resizing:

Domain assignment resizes any/all array(s) defined on the domain:

```chapel
var dom = {1..10};
var arr: [dom] int; // 10 integers

dom = {2..20};
// arr is now 19 integers
```

I suggest checking the specs or testing it to see if the data in the indices in the intersection are preserved or not.

**Comment by LouisJenkinsCS** [comment]
@e-kayrakli 

You mentioned often things which "aren't worth my time", but not really as to *where* it should be directed most. Beyond small additions to my script/makefile and some syntactic/semantic changes. These changes don't feel as important really, so I'm not sure what else I should prioritize rather than trying to get NQueens to work. Normally I switch to another problem so I'm not stuck, but right now the other things I suggested aren't worth investigating.

**Comment by e-kayrakli** [comment]
@LouisJenkinsCS -- sorry for confusion.. I think I have no problem with you going back to actual development and getting things working.
